version: '3.8'

services:
  api:
    build: .
    container_name: doclens-api
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate

  ui:
    build: .
    container_name: doclens-ui
    command: streamlit run src/ui.py --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api